[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
FRGLatticeEvaluation = "a44b592b-45f7-4b02-a4df-e53b23f0d903"
HDF5Helpers = "2867bddc-101e-43c9-836d-7ce2d0afa337"
PMFRG = "37d616f8-0bcb-4e18-9a76-f5d18f52650d"
PMFRGEvaluation = "12f9d3e0-c7ac-4982-a146-f6f67cbda763"
SpinFRGLattices = "053fb7f8-31b7-4f68-aef8-4452b415dd8c"
